// nuxtjs-tailwindcss/components/Pages/Restaurant/DishDetails/Reviews.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md mb-[25px]"
  >
    <div
      class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between"
    >
      <div class="trezo-card-title">
        <h5 class="!mb-0">Reviews</h5>
      </div>
    </div>

    <div class="trezo-card-content">
      <div class="table-responsive overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr>
              <th
                v-for="header in headers"
                :key="header.key"
                class="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[11px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0"
              >
                {{ header.label }}
              </th>
            </tr>
          </thead>

          <tbody class="text-black dark:text-white">
            <tr v-for="review in paginatedReviews" :key="review.id">
              <td
                class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top"
              >
                <span
                  class="block text-xs font-semibold text-gray-600 dark:text-gray-400"
                >
                  {{ review.id }}
                </span>
              </td>
              <td
                class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top"
              >
                <div class="flex items-center gap-[10px]">
                  <div class="rounded-full w-[30px]">
                    <img
                      :src="review.avatar"
                      class="inline-block rounded-full"
                      alt="user-image"
                    />
                  </div>
                  <span class="font-semibold inline-block">
                    {{ review.name }}
                  </span>
                </div>
              </td>
              <td
                class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top"
              >
                <div class="flex items-center leading-none gap-[2px]">
                  <i class="ri-star-fill text-orange-500"></i>
                  <span
                    class="block relative top-px text-xs text-gray-500 dark:text-gray-400 ltr:ml-[2px] rtl:mr-[2px] font-semibold"
                  >
                    {{ review.rating }}
                  </span>
                </div>
              </td>
              <td
                class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top"
              >
                <div class="whitespace-normal w-[620px]">
                  <span
                    class="block text-xs mb-[5px] font-semibold text-gray-600 dark:text-gray-400"
                  >
                    {{ review.title }}
                  </span>
                  <p class="text-xs text-gray-500 dark:text-gray-400">
                    {{ review.comment }}
                  </p>
                </div>
              </td>
              <td
                class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top"
              >
                <span
                  class="block text-xs font-semibold text-gray-600 dark:text-gray-400"
                >
                  {{ formatDate(review.date) }}
                </span>
              </td>
              <td
                class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top"
              >
                <div class="flex items-center gap-[9px]">
                  <button
                    type="button"
                    class="text-primary-500 leading-none custom-tooltip"
                    data-text="View"
                  >
                    <i class="material-symbols-outlined !text-md">
                      visibility
                    </i>
                  </button>
                  <button
                    type="button"
                    class="text-gray-500 dark:text-gray-400 leading-none custom-tooltip"
                    data-text="Edit"
                  >
                    <i class="material-symbols-outlined !text-md"> edit </i>
                  </button>
                  <button
                    type="button"
                    class="text-danger-500 leading-none custom-tooltip"
                    data-text="Delete"
                  >
                    <i class="material-symbols-outlined !text-md"> delete </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="pt-[11px] sm:flex sm:items-center justify-between">
        <p class="!mb-0 text-xs">
          Showing {{ showingStart }}-{{ showingEnd }} of
          {{ totalReviews }} results
        </p>
        <ol class="mt-[10px] sm:mt-0">
          <li
            class="inline-block mx-[1px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0"
          >
            <button
              :disabled="currentPage === 1"
              @click="prevPage"
              class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="opacity-0"> 0 </span>
              <i
                class="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2"
              >
                chevron_left
              </i>
            </button>
          </li>
          <li
            v-for="page in totalPages"
            :key="page"
            class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0"
          >
            <button
              @click="goToPage(page)"
              class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500"
              :class="{
                'border-primary-500 bg-primary-500 text-white':
                  currentPage === page,
                'border-gray-100 dark:border-[#172036]': currentPage !== page,
              }"
            >
              {{ page }}
            </button>
          </li>
          <li
            class="inline-block mx-[1px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0"
          >
            <button
              :disabled="currentPage === totalPages"
              @click="nextPage"
              class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="opacity-0"> 0 </span>
              <i
                class="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2"
              >
                chevron_right
              </i>
            </button>
          </li>
        </ol>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

import image1 from "@/assets/images/users/user58.jpg";
import image2 from "@/assets/images/users/user59.jpg";
import image3 from "@/assets/images/users/user60.jpg";

interface Review {
  id: string;
  avatar: string;
  name: string;
  rating: number;
  title: string;
  comment: string;
  date: Date | string;
}

export default defineComponent({
  name: "Reviews",
  setup() {
    const currentPage = ref(1);
    const itemsPerPage = ref(3);

    const headers = ref([
      { key: "id", label: "User ID" },
      { key: "name", label: "Customer Name" },
      { key: "rating", label: "Ratings" },
      { key: "comment", label: "Reviews" },
      { key: "date", label: "Date" },
      { key: "actions", label: "" },
    ]);

    const reviews = ref<Review[]>([
      {
        id: "#001",
        avatar: image1,
        name: "Joanna Watson",
        rating: 5.0,
        title: "Amazing Ambiance and Delicious Food!",
        comment:
          "Trezo was a fantastic dining experience. The ambiance is warm and inviting, perfect for a date night or celebration. I ordered the truffle pasta, which was rich and perfectly seasoned. The service was impeccable, and the staff made us feel like family. Highly recommend!",
        date: "2025-11-13",
      },
      {
        id: "#002",
        avatar: image2,
        name: "Jenelia Anderson",
        rating: 4.9,
        title: "Best Brunch Spot in Town",
        comment:
          "Visited Trezo for brunch with friends, and it exceeded our expectations. The avocado toast was fresh, and their mimosas were spot-on. Our server was attentive without being intrusive. Definitely coming back!",
        date: "2025-11-14",
      },
      {
        id: "#003",
        avatar: image3,
        name: "Jonathon Ronan",
        rating: 4.0,
        title: "Good Food, Slow Service",
        comment:
          "The food at Trezo was delicious, but the service was a bit slow. We had to wait a while for our appetizers, and our main course was delayed. It's a nice spot, but they could work on speeding up their service.",
        date: "2025-11-15",
      },
      {
        id: "#004",
        avatar: image3,
        name: "Jonathon Ronan",
        rating: 4.0,
        title: "Good Food, Slow Service",
        comment:
          "The food at Trezo was delicious, but the service was a bit slow. We had to wait a while for our appetizers, and our main course was delayed. It's a nice spot, but they could work on speeding up their service.",
        date: "2025-11-15",
      },
      {
        id: "#005",
        avatar: image1,
        name: "Joanna Watson",
        rating: 5.0,
        title: "Amazing Ambiance and Delicious Food!",
        comment:
          "Trezo was a fantastic dining experience. The ambiance is warm and inviting, perfect for a date night or celebration. I ordered the truffle pasta, which was rich and perfectly seasoned. The service was impeccable, and the staff made us feel like family. Highly recommend!",
        date: "2025-11-13",
      },
      {
        id: "#006",
        avatar: image2,
        name: "Jenelia Anderson",
        rating: 4.9,
        title: "Best Brunch Spot in Town",
        comment:
          "Visited Trezo for brunch with friends, and it exceeded our expectations. The avocado toast was fresh, and their mimosas were spot-on. Our server was attentive without being intrusive. Definitely coming back!",
        date: "2025-11-14",
      },
    ]);

    const totalReviews = computed(() => reviews.value.length);

    const totalPages = computed(() =>
      Math.ceil(totalReviews.value / itemsPerPage.value)
    );

    const paginatedReviews = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage.value;
      const end = start + itemsPerPage.value;
      return reviews.value.slice(start, end);
    });

    const showingStart = computed(
      () => (currentPage.value - 1) * itemsPerPage.value + 1
    );

    const showingEnd = computed(() => {
      const end = currentPage.value * itemsPerPage.value;
      return end > totalReviews.value ? totalReviews.value : end;
    });

    const formatDate = (date: Date | string): string => {
      if (typeof date === "string") {
        date = new Date(date);
      }
      return date.toLocaleDateString("en-US", {
        day: "numeric",
        month: "short",
        year: "numeric",
      });
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    const goToPage = (page: number) => {
      if (page >= 1 && page <= totalPages.value) {
        currentPage.value = page;
      }
    };

    return {
      currentPage,
      headers,
      reviews,
      totalReviews,
      totalPages,
      paginatedReviews,
      showingStart,
      showingEnd,
      formatDate,
      prevPage,
      nextPage,
      goToPage,
    };
  },
});
</script>

// react-nextjs-tailwindcss/src/components/Restaurant/Reviews.tsx
"use client";

import React, { useState } from "react";
import Image from "next/image";

interface Rating {
  id: string;
  userId: string;
  customerName: string;
  avatar: string;
  rating: number;
  title: string;
  review: string;
  date: string;
}

const Reviews: React.FC = () => {
  // Sample data - in a real app, this would come from an API
  const allRatings: Rating[] = [
    {
      id: "1",
      userId: "#001",
      customerName: "Joanna Watson",
      avatar: "/images/users/user58.jpg",
      rating: 5.0,
      title: "Amazing Ambiance and Delicious Food!",
      review:
        "Trezo was a fantastic dining experience. The ambiance is warm and inviting, perfect for a date night or celebration. I ordered the truffle pasta, which was rich and perfectly seasoned. The service was impeccable, and the staff made us feel like family. Highly recommend!",
      date: "13 Nov, 25",
    },
    {
      id: "2",
      userId: "#002",
      customerName: "Jenelia Anderson",
      avatar: "/images/users/user59.jpg",
      rating: 4.9,
      title: "Best Brunch Spot in Town",
      review:
        "Visited Trezo for brunch with friends, and it exceeded our expectations. The avocado toast was fresh, and their mimosas were spot-on. Our server was attentive without being intrusive. Definitely coming back!",
      date: "14 Nov, 25",
    },
    {
      id: "3",
      userId: "#003",
      customerName: "Michael Johnson",
      avatar: "/images/users/user60.jpg",
      rating: 4.5,
      title: "Great Service, Good Food",
      review:
        "The steak was cooked perfectly to my liking. Service was excellent with timely check-ins. The atmosphere was lively but not too loud. Would recommend for business dinners.",
      date: "15 Nov, 25",
    },
    {
      id: "4",
      userId: "#004",
      customerName: "Sarah Williams",
      avatar: "/images/users/user61.jpg",
      rating: 5.0,
      title: "Perfect Anniversary Dinner",
      review:
        "Trezo made our anniversary special. They gave us a complimentary dessert with a candle. The wine pairing suggestion was excellent. Every dish was beautifully presented.",
      date: "16 Nov, 25",
    },
    {
      id: "5",
      userId: "#005",
      customerName: "David Brown",
      avatar: "/images/users/user62.jpg",
      rating: 4.0,
      title: "Good but pricey",
      review:
        "Food quality is excellent but portions are small for the price. The cocktails are creative and well-made. Would come back for special occasions.",
      date: "17 Nov, 25",
    },
    {
      id: "6",
      userId: "#006",
      customerName: "Emily Davis",
      avatar: "/images/users/user63.jpg",
      rating: 4.7,
      title: "Lovely outdoor seating",
      review:
        "The garden area is beautiful in the evening. The seafood pasta was delicious. Service was a bit slow but friendly. Great place for a romantic evening.",
      date: "18 Nov, 25",
    },
    {
      id: "7",
      userId: "#007",
      customerName: "Robert Wilson",
      avatar: "/images/users/user64.jpg",
      rating: 3.5,
      title: "Decent experience",
      review:
        "Food was good but not exceptional. The noise level was high making conversation difficult. Might try again during lunch hours.",
      date: "19 Nov, 25",
    },
    {
      id: "8",
      userId: "#008",
      customerName: "Jennifer Taylor",
      avatar: "/images/users/user65.jpg",
      rating: 5.0,
      title: "Exceptional from start to finish",
      review:
        "Every aspect of our meal was perfect. The chef came out to check on us. The sommelier's wine recommendation was spot on. Worth every penny.",
      date: "20 Nov, 25",
    },
  ];

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 3;

  // Calculate pagination
  const totalItems = allRatings.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentRatings = allRatings.slice(startIndex, endIndex);

  // Handle page change
  const handlePageChange = (page: number) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
    }
  };

  // Render star rating
  const renderStars = (rating: number) => {
    const stars = [];
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 >= 0.5;

    for (let i = 0; i < fullStars; i++) {
      stars.push(
        <i key={`full-${i}`} className="ri-star-fill text-orange-500"></i>
      );
    }

    if (hasHalfStar) {
      stars.push(
        <i key="half" className="ri-star-half-fill text-orange-500"></i>
      );
    }

    const emptyStars = 5 - stars.length;
    for (let i = 0; i < emptyStars; i++) {
      stars.push(
        <i key={`empty-${i}`} className="ri-star-line text-orange-500"></i>
      );
    }

    return (
      <div className="flex items-center leading-none gap-[2px]">
        {stars}
        <span className="block relative top-px text-xs text-gray-500 dark:text-gray-400 ltr:ml-[2px] rtl:mr-[2px] font-semibold">
          {rating.toFixed(1)}
        </span>
      </div>
    );
  };

  return (
    <div className="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md mb-[25px]">
      <div className="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
        <div className="trezo-card-title">
          <h5 className="!mb-0">Reviews</h5>
        </div>
      </div>

      <div className="trezo-card-content">
        <div className="table-responsive overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr>
                <th className="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[11px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                  User ID
                </th>
                <th className="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[11px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                  Customer Name
                </th>
                <th className="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[11px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                  Ratings
                </th>
                <th className="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[11px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                  Reviews
                </th>
                <th className="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[11px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                  Date
                </th>
                <th className="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[11px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0"></th>
              </tr>
            </thead>

            <tbody className="text-black dark:text-white">
              {currentRatings.map((rating) => (
                <tr key={rating.id}>
                  <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top">
                    <span className="block text-xs font-semibold text-gray-600 dark:text-gray-400">
                      {rating.userId}
                    </span>
                  </td>
                  <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top">
                    <div className="flex items-center gap-[10px]">
                      <div className="rounded-full w-[30px] h-[30px] overflow-hidden">
                        <Image
                          src={rating.avatar}
                          className="w-full h-full object-cover"
                          alt="user-image"
                          width={30}
                          height={30}
                        />
                      </div>
                      <span className="font-semibold inline-block">
                        {rating.customerName}
                      </span>
                    </div>
                  </td>
                  <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top">
                    {renderStars(rating.rating)}
                  </td>
                  <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top">
                    <div className="whitespace-normal w-[620px]">
                      <span className="block text-xs mb-[5px] font-semibold text-gray-600 dark:text-gray-400">
                        {rating.title}
                      </span>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        {rating.review}
                      </p>
                    </div>
                  </td>
                  <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top">
                    <span className="block text-xs font-semibold text-gray-600 dark:text-gray-400">
                      {rating.date}
                    </span>
                  </td>
                  <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0 align-top">
                    <div className="flex items-center gap-[9px]">
                      <button
                        type="button"
                        className="text-primary-500 leading-none custom-tooltip"
                      >
                        <i className="material-symbols-outlined !text-md">
                          visibility
                        </i>
                      </button>
                      <button
                        type="button"
                        className="text-gray-500 dark:text-gray-400 leading-none custom-tooltip"
                      >
                        <i className="material-symbols-outlined !text-md">
                          edit
                        </i>
                      </button>
                      <button
                        type="button"
                        className="text-danger-500 leading-none custom-tooltip"
                      >
                        <i className="material-symbols-outlined !text-md">
                          delete
                        </i>
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="pt-[11px] sm:flex sm:items-center justify-between">
          <p className="!mb-0 !text-xs">
            Showing {startIndex + 1} to {Math.min(endIndex, totalItems)} of{" "}
            {totalItems} results
          </p>
          <ol className="mt-[10px] sm:mt-0 flex items-center">
            <li className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
              <button
                onClick={() => handlePageChange(currentPage - 1)}
                disabled={currentPage === 1}
                className={`w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border ${
                  currentPage === 1
                    ? "border-gray-200 dark:border-[#172036] text-gray-400 cursor-not-allowed"
                    : "border-gray-100 dark:border-[#172036] hover:bg-primary-500 hover:text-white hover:border-primary-500"
                }`}
              >
                <span className="opacity-0">0</span>
                <i className="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                  chevron_left
                </i>
              </button>
            </li>

            {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
              <li
                key={page}
                className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0"
              >
                <button
                  onClick={() => handlePageChange(page)}
                  className={`w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md ${
                    currentPage === page
                      ? "border border-primary-500 bg-primary-500 text-white"
                      : "border border-gray-100 dark:border-[#172036] hover:bg-primary-500 hover:text-white hover:border-primary-500"
                  }`}
                >
                  {page}
                </button>
              </li>
            ))}

            <li className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
              <button
                onClick={() => handlePageChange(currentPage + 1)}
                disabled={currentPage === totalPages}
                className={`w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border ${
                  currentPage === totalPages
                    ? "border-gray-200 dark:border-[#172036] text-gray-400 cursor-not-allowed"
                    : "border-gray-100 dark:border-[#172036] hover:bg-primary-500 hover:text-white hover:border-primary-500"
                }`}
              >
                <span className="opacity-0">0</span>
                <i className="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                  chevron_right
                </i>
              </button>
            </li>
          </ol>
        </div>
      </div>
    </div>
  );
};

export default Reviews;
